name: License CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Install licensed
        run: |
          cd $RUNNER_TEMP
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/releases/download/2.12.2/licensed-2.12.2-linux-x64.tar.gz
          sudo tar -xzf licensed.tar.gz
          sudo mv licensed /usr/local/bin/licensed
      - name: Check licensed status
        run: licensed status
